version: "3.4"
services:
  browserless:
    image: browserless/chrome:latest
    restart: always
    network_mode: host

  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-latest
    restart: always
    ports:
      - 8079:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/umami

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: umami
      POSTGRES_PASSWORD: password
