version: '3.4'
services:

  devcontainer:
    build:
      context: .
      dockerfile: dockerfile.devcontainer
    volumes:
      - .:/workspace:cached
      - ${PNPM_STORE_PATH}:/pnpm-store:cached
    network_mode: host
    command: /bin/sh -c "while true; do sleep 30; done"

  browserless:
    image: browserless/chrome:latest
    restart: always
    ports:
      - 3000:3000
    network_mode: host
