---
- name: deploy yapms test
  hosts: all
  become: true

  tasks:

    - name: copy caddy file
      copy:
        src: Caddyfile
        dest: /home/core/Caddyfile

    - name: deploy caddy
      community.docker.docker_container:
        name: caddy
        image: caddy:2.6.4-alpine
        restart_policy: always
        volumes:
          - /home/core/Caddyfile:/etc/caddy/Caddyfile
        ports:
          - 80:80
          - 443:443
        network_mode: host

    - name: deploy yapms
      community.docker.docker_container:
        name: yapms
        image: ghcr.io/yapms/yapms-yapms:ansible
        restart_policy: always
        ports:
          - 8081:3000

    - name: deploy pocketbase
      community.docker.docker_container:
        name: pocketbase
        image: ghcr.io/yapms/yapms-pocketbase:ansible
        restart_policy: always
        ports:
          - 8080:8080
    
    - name: deploy browserless
      community.docker.docker_container:
        name: browserless
        image: browserless/chrome:latest
        restart_policy: always
        network_mode: host
