name: Build YAPms Image

on:
  push:
    branches:
      - ansible

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            DOTENV_VAULT_KEY=${{ secrets.DOTENV_VAULT_KEY }}
          push: true
          tags: test-tags
          labels: test-labels
          # tags: ${{ steps.metadata.outputs.tags }}-yapms
          # labels: ${{ steps.metadata.outputs.labels }}-yapms