name: Deploy Docs

on:
  push:
    tags: [v*]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: withastro/action@v1
        with:
          path: ./apps/docs

      - uses: actions/deploy-pages@v2
